<?php
/**
 * CancellationReason
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Platform API
 *
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayoneCommercePlatform\Sdk\Domain;
use \PayoneCommercePlatform\Sdk\ObjectSerializer;

/**
 * CancellationReason Class Doc Comment
 *
 * @category Class
 * @description Reason why an order was cancelled. Possible values:         * CONSUMER_REQUEST - The consumer requested a cancellation of the Order * UNDELIVERABLE - The merchant cannot fulfill the Order * DUPLICATE - The Order was created twice accidentally * FRAUDULENT- Consumer turned out to be a fraudster * ORDER_SHIPPED_IN_FULL - The merchant shipped everything and wants to cancel the remaining authorized amount of the Order * AUTOMATED_SHIPMENT_FAILED - A technical error was thrown during an automated shipment API call rendering the Order impossible to complete  Mandatory for PAYONE Buy Now, Pay Later (BNPL): * 3390 - PAYONE Secured Invoice * 3391 - PAYONE Secured Installment * 3392 - PAYONE Secured Direct Debit
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CancellationReason
{
    /**
     * Possible values of this enum
     */
    public const CONSUMER_REQUEST = 'CONSUMER_REQUEST';

    public const UNDELIVERABLE = 'UNDELIVERABLE';

    public const DUPLICATE = 'DUPLICATE';

    public const FRAUDULENT = 'FRAUDULENT';

    public const ORDER_SHIPPED_IN_FULL = 'ORDER_SHIPPED_IN_FULL';

    public const AUTOMATED_SHIPMENT_FAILED = 'AUTOMATED_SHIPMENT_FAILED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONSUMER_REQUEST,
            self::UNDELIVERABLE,
            self::DUPLICATE,
            self::FRAUDULENT,
            self::ORDER_SHIPPED_IN_FULL,
            self::AUTOMATED_SHIPMENT_FAILED
        ];
    }
}


