<?php
/**
 * CardPaymentDetails
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Platform API
 *
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayoneCommercePlatform\Sdk\Domain;

use \ArrayAccess;
use \PayoneCommercePlatform\Sdk\ObjectSerializer;

/**
 * CardPaymentDetails Class Doc Comment
 *
 * @category Class
 * @description Information for card payments realized at a POS.
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CardPaymentDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CardPaymentDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'maskedCardNumber' => 'string',
        'paymentProcessingToken' => 'string',
        'reportingToken' => 'string',
        'cardAuthorizationId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'maskedCardNumber' => null,
        'paymentProcessingToken' => null,
        'reportingToken' => null,
        'cardAuthorizationId' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'maskedCardNumber' => false,
        'paymentProcessingToken' => false,
        'reportingToken' => false,
        'cardAuthorizationId' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'maskedCardNumber' => 'maskedCardNumber',
        'paymentProcessingToken' => 'paymentProcessingToken',
        'reportingToken' => 'reportingToken',
        'cardAuthorizationId' => 'cardAuthorizationId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'maskedCardNumber' => 'setMaskedCardNumber',
        'paymentProcessingToken' => 'setPaymentProcessingToken',
        'reportingToken' => 'setReportingToken',
        'cardAuthorizationId' => 'setCardAuthorizationId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'maskedCardNumber' => 'getMaskedCardNumber',
        'paymentProcessingToken' => 'getPaymentProcessingToken',
        'reportingToken' => 'getReportingToken',
        'cardAuthorizationId' => 'getCardAuthorizationId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('maskedCardNumber', $data ?? [], null);
        $this->setIfExists('paymentProcessingToken', $data ?? [], null);
        $this->setIfExists('reportingToken', $data ?? [], null);
        $this->setIfExists('cardAuthorizationId', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['maskedCardNumber']) && (mb_strlen($this->container['maskedCardNumber']) > 40)) {
            $invalidProperties[] = "invalid value for 'maskedCardNumber', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['paymentProcessingToken']) && (mb_strlen($this->container['paymentProcessingToken']) > 40)) {
            $invalidProperties[] = "invalid value for 'paymentProcessingToken', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['reportingToken']) && (mb_strlen($this->container['reportingToken']) > 40)) {
            $invalidProperties[] = "invalid value for 'reportingToken', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['cardAuthorizationId']) && (mb_strlen($this->container['cardAuthorizationId']) > 8)) {
            $invalidProperties[] = "invalid value for 'cardAuthorizationId', the character length must be smaller than or equal to 8.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets maskedCardNumber
     *
     * @return string|null
     */
    public function getMaskedCardNumber()
    {
        return $this->container['maskedCardNumber'];
    }

    /**
     * Sets maskedCardNumber
     *
     * @param string|null $maskedCardNumber Reference to the card of the transaction.
     *
     * @return self
     */
    public function setMaskedCardNumber($maskedCardNumber)
    {
        if (is_null($maskedCardNumber)) {
            throw new \InvalidArgumentException('non-nullable maskedCardNumber cannot be null');
        }
        if ((mb_strlen($maskedCardNumber) > 40)) {
            throw new \InvalidArgumentException('invalid length for $maskedCardNumber when calling CardPaymentDetails., must be smaller than or equal to 40.');
        }

        $this->container['maskedCardNumber'] = $maskedCardNumber;

        return $this;
    }

    /**
     * Gets paymentProcessingToken
     *
     * @return string|null
     */
    public function getPaymentProcessingToken()
    {
        return $this->container['paymentProcessingToken'];
    }

    /**
     * Sets paymentProcessingToken
     *
     * @param string|null $paymentProcessingToken ID of the token. This property is populated when the payment was done with a token.
     *
     * @return self
     */
    public function setPaymentProcessingToken($paymentProcessingToken)
    {
        if (is_null($paymentProcessingToken)) {
            throw new \InvalidArgumentException('non-nullable paymentProcessingToken cannot be null');
        }
        if ((mb_strlen($paymentProcessingToken) > 40)) {
            throw new \InvalidArgumentException('invalid length for $paymentProcessingToken when calling CardPaymentDetails., must be smaller than or equal to 40.');
        }

        $this->container['paymentProcessingToken'] = $paymentProcessingToken;

        return $this;
    }

    /**
     * Gets reportingToken
     *
     * @return string|null
     */
    public function getReportingToken()
    {
        return $this->container['reportingToken'];
    }

    /**
     * Sets reportingToken
     *
     * @param string|null $reportingToken Token to identify the card in the reporting.
     *
     * @return self
     */
    public function setReportingToken($reportingToken)
    {
        if (is_null($reportingToken)) {
            throw new \InvalidArgumentException('non-nullable reportingToken cannot be null');
        }
        if ((mb_strlen($reportingToken) > 40)) {
            throw new \InvalidArgumentException('invalid length for $reportingToken when calling CardPaymentDetails., must be smaller than or equal to 40.');
        }

        $this->container['reportingToken'] = $reportingToken;

        return $this;
    }

    /**
     * Gets cardAuthorizationId
     *
     * @return string|null
     */
    public function getCardAuthorizationId()
    {
        return $this->container['cardAuthorizationId'];
    }

    /**
     * Sets cardAuthorizationId
     *
     * @param string|null $cardAuthorizationId Identifier for a successful authorization, reversal or refund. Usually provided by the issuer system. Only provided for card payments.
     *
     * @return self
     */
    public function setCardAuthorizationId($cardAuthorizationId)
    {
        if (is_null($cardAuthorizationId)) {
            throw new \InvalidArgumentException('non-nullable cardAuthorizationId cannot be null');
        }
        if ((mb_strlen($cardAuthorizationId) > 8)) {
            throw new \InvalidArgumentException('invalid length for $cardAuthorizationId when calling CardPaymentDetails., must be smaller than or equal to 8.');
        }

        $this->container['cardAuthorizationId'] = $cardAuthorizationId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


