<?php
/**
 * MandateRecurrenceType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Platform API
 *
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayoneCommercePlatform\Sdk\Domain;
use \PayoneCommercePlatform\Sdk\ObjectSerializer;

/**
 * MandateRecurrenceType Class Doc Comment
 *
 * @category Class
 * @description Specifies whether the mandate is for one-off or recurring payments. Possible values are: * UNIQUE * RECURRING
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MandateRecurrenceType
{
    /**
     * Possible values of this enum
     */
    public const UNIQUE = 'UNIQUE';

    public const RECURRING = 'RECURRING';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNIQUE,
            self::RECURRING
        ];
    }
}


