<?php
/**
 * MobilePaymentMethodSpecificInput
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Platform API
 *
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayoneCommercePlatform\Sdk\Domain;

use ArrayAccess;
use PayoneCommercePlatform\Sdk\ObjectSerializer;

/**
 * MobilePaymentMethodSpecificInput Class Doc Comment
 *
 * @category Class
 * @description Object containing the specific input details for mobile payments.
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MobilePaymentMethodSpecificInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MobilePaymentMethodSpecificInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'paymentProductId' => 'int',
        'authorizationMode' => '\PayoneCommercePlatform\Sdk\Domain\AuthorizationMode',
        'encryptedPaymentData' => 'string',
        'publicKeyHash' => 'string',
        'ephemeralKey' => 'string',
        'paymentProduct302SpecificInput' => '\PayoneCommercePlatform\Sdk\Domain\PaymentProduct320SpecificInput'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'paymentProductId' => 'int32',
        'authorizationMode' => null,
        'encryptedPaymentData' => null,
        'publicKeyHash' => null,
        'ephemeralKey' => null,
        'paymentProduct302SpecificInput' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'paymentProductId' => false,
        'authorizationMode' => false,
        'encryptedPaymentData' => false,
        'publicKeyHash' => false,
        'ephemeralKey' => false,
        'paymentProduct302SpecificInput' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'paymentProductId' => 'paymentProductId',
        'authorizationMode' => 'authorizationMode',
        'encryptedPaymentData' => 'encryptedPaymentData',
        'publicKeyHash' => 'publicKeyHash',
        'ephemeralKey' => 'ephemeralKey',
        'paymentProduct302SpecificInput' => 'paymentProduct302SpecificInput'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'paymentProductId' => 'setPaymentProductId',
        'authorizationMode' => 'setAuthorizationMode',
        'encryptedPaymentData' => 'setEncryptedPaymentData',
        'publicKeyHash' => 'setPublicKeyHash',
        'ephemeralKey' => 'setEphemeralKey',
        'paymentProduct302SpecificInput' => 'setPaymentProduct302SpecificInput'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'paymentProductId' => 'getPaymentProductId',
        'authorizationMode' => 'getAuthorizationMode',
        'encryptedPaymentData' => 'getEncryptedPaymentData',
        'publicKeyHash' => 'getPublicKeyHash',
        'ephemeralKey' => 'getEphemeralKey',
        'paymentProduct302SpecificInput' => 'getPaymentProduct302SpecificInput'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('paymentProductId', $data ?? [], null);
        $this->setIfExists('authorizationMode', $data ?? [], null);
        $this->setIfExists('encryptedPaymentData', $data ?? [], null);
        $this->setIfExists('publicKeyHash', $data ?? [], null);
        $this->setIfExists('ephemeralKey', $data ?? [], null);
        $this->setIfExists('paymentProduct302SpecificInput', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['paymentProductId']) && ($this->container['paymentProductId'] > 99999)) {
            $invalidProperties[] = "invalid value for 'paymentProductId', must be smaller than or equal to 99999.";
        }

        if (!is_null($this->container['paymentProductId']) && ($this->container['paymentProductId'] < 0)) {
            $invalidProperties[] = "invalid value for 'paymentProductId', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets paymentProductId
     *
     * @return int|null
     */
    public function getPaymentProductId()
    {
        return $this->container['paymentProductId'];
    }

    /**
     * Sets paymentProductId
     *
     * @param int|null $paymentProductId Payment product identifier - please check product documentation for a full overview of possible values.
     *
     * @return self
     */
    public function setPaymentProductId($paymentProductId)
    {
        if (is_null($paymentProductId)) {
            throw new \InvalidArgumentException('non-nullable paymentProductId cannot be null');
        }

        if (($paymentProductId > 99999)) {
            throw new \InvalidArgumentException('invalid value for $paymentProductId when calling MobilePaymentMethodSpecificInput., must be smaller than or equal to 99999.');
        }
        if (($paymentProductId < 0)) {
            throw new \InvalidArgumentException('invalid value for $paymentProductId when calling MobilePaymentMethodSpecificInput., must be bigger than or equal to 0.');
        }

        $this->container['paymentProductId'] = $paymentProductId;

        return $this;
    }

    /**
     * Gets authorizationMode
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\AuthorizationMode|null
     */
    public function getAuthorizationMode()
    {
        return $this->container['authorizationMode'];
    }

    /**
     * Sets authorizationMode
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\AuthorizationMode|null $authorizationMode authorizationMode
     *
     * @return self
     */
    public function setAuthorizationMode($authorizationMode)
    {
        if (is_null($authorizationMode)) {
            throw new \InvalidArgumentException('non-nullable authorizationMode cannot be null');
        }
        $this->container['authorizationMode'] = $authorizationMode;

        return $this;
    }

    /**
     * Gets encryptedPaymentData
     *
     * @return string|null
     */
    public function getEncryptedPaymentData()
    {
        return $this->container['encryptedPaymentData'];
    }

    /**
     * Sets encryptedPaymentData
     *
     * @param string|null $encryptedPaymentData The payment data if we will do the decryption of the encrypted payment data. Typically you'd use encryptedCustomerInput in the root of the create payment request to provide the encrypted payment data instead.
     *
     * @return self
     */
    public function setEncryptedPaymentData($encryptedPaymentData)
    {
        if (is_null($encryptedPaymentData)) {
            throw new \InvalidArgumentException('non-nullable encryptedPaymentData cannot be null');
        }
        $this->container['encryptedPaymentData'] = $encryptedPaymentData;

        return $this;
    }

    /**
     * Gets publicKeyHash
     *
     * @return string|null
     */
    public function getPublicKeyHash()
    {
        return $this->container['publicKeyHash'];
    }

    /**
     * Sets publicKeyHash
     *
     * @param string|null $publicKeyHash Public Key Hash A unique identifier to retrieve key used by Apple to encrypt information.
     *
     * @return self
     */
    public function setPublicKeyHash($publicKeyHash)
    {
        if (is_null($publicKeyHash)) {
            throw new \InvalidArgumentException('non-nullable publicKeyHash cannot be null');
        }
        $this->container['publicKeyHash'] = $publicKeyHash;

        return $this;
    }

    /**
     * Gets ephemeralKey
     *
     * @return string|null
     */
    public function getEphemeralKey()
    {
        return $this->container['ephemeralKey'];
    }

    /**
     * Sets ephemeralKey
     *
     * @param string|null $ephemeralKey Ephemeral Key A unique generated key used by Apple to encrypt data.
     *
     * @return self
     */
    public function setEphemeralKey($ephemeralKey)
    {
        if (is_null($ephemeralKey)) {
            throw new \InvalidArgumentException('non-nullable ephemeralKey cannot be null');
        }
        $this->container['ephemeralKey'] = $ephemeralKey;

        return $this;
    }

    /**
     * Gets paymentProduct302SpecificInput
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\PaymentProduct320SpecificInput|null
     */
    public function getPaymentProduct302SpecificInput()
    {
        return $this->container['paymentProduct302SpecificInput'];
    }

    /**
     * Sets paymentProduct302SpecificInput
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\PaymentProduct320SpecificInput|null $paymentProduct302SpecificInput paymentProduct302SpecificInput
     *
     * @return self
     */
    public function setPaymentProduct302SpecificInput($paymentProduct302SpecificInput)
    {
        if (is_null($paymentProduct302SpecificInput)) {
            throw new \InvalidArgumentException('non-nullable paymentProduct302SpecificInput cannot be null');
        }
        $this->container['paymentProduct302SpecificInput'] = $paymentProduct302SpecificInput;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
