<?php
/**
 * PatchCheckoutRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Platform API
 *
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayoneCommercePlatform\Sdk\Domain;

use \ArrayAccess;
use \PayoneCommercePlatform\Sdk\ObjectSerializer;

/**
 * PatchCheckoutRequest Class Doc Comment
 *
 * @category Class
 * @description An existing shopping cart of a Checkout will not be overwritten with the Patch request. New items can be added to the shoppingCart by providing them in the request. To change existing items (delete, modify or add), the respective itemId must be provided. An item can be completely removed if quantity &#x3D; 0 is provided.  The price of an item can be changed as long as no payment has happened for this item (i.e. as long as an item has no specific status). Items with a status can no longer be removed entirely, however the quantity can be increased or decreased (for items without payment) by using the itemId.  If no amountOfMoney for the Checkout is provided, the platform will calculate the respective amount based on the cartItem productPrice and productQuantity.
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PatchCheckoutRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PatchCheckoutRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'amountOfMoney' => '\PayoneCommercePlatform\Sdk\Domain\AmountOfMoney',
        'references' => '\PayoneCommercePlatform\Sdk\Domain\CheckoutReferences',
        'shipping' => '\PayoneCommercePlatform\Sdk\Domain\Shipping',
        'shoppingCart' => '\PayoneCommercePlatform\Sdk\Domain\ShoppingCartPatch',
        'paymentMethodSpecificInput' => '\PayoneCommercePlatform\Sdk\Domain\PaymentMethodSpecificInput',
        'paymentReferences' => '\PayoneCommercePlatform\Sdk\Domain\References'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'amountOfMoney' => null,
        'references' => null,
        'shipping' => null,
        'shoppingCart' => null,
        'paymentMethodSpecificInput' => null,
        'paymentReferences' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'amountOfMoney' => false,
        'references' => false,
        'shipping' => false,
        'shoppingCart' => false,
        'paymentMethodSpecificInput' => false,
        'paymentReferences' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amountOfMoney' => 'amountOfMoney',
        'references' => 'references',
        'shipping' => 'shipping',
        'shoppingCart' => 'shoppingCart',
        'paymentMethodSpecificInput' => 'paymentMethodSpecificInput',
        'paymentReferences' => 'paymentReferences'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amountOfMoney' => 'setAmountOfMoney',
        'references' => 'setReferences',
        'shipping' => 'setShipping',
        'shoppingCart' => 'setShoppingCart',
        'paymentMethodSpecificInput' => 'setPaymentMethodSpecificInput',
        'paymentReferences' => 'setPaymentReferences'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amountOfMoney' => 'getAmountOfMoney',
        'references' => 'getReferences',
        'shipping' => 'getShipping',
        'shoppingCart' => 'getShoppingCart',
        'paymentMethodSpecificInput' => 'getPaymentMethodSpecificInput',
        'paymentReferences' => 'getPaymentReferences'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('amountOfMoney', $data ?? [], null);
        $this->setIfExists('references', $data ?? [], null);
        $this->setIfExists('shipping', $data ?? [], null);
        $this->setIfExists('shoppingCart', $data ?? [], null);
        $this->setIfExists('paymentMethodSpecificInput', $data ?? [], null);
        $this->setIfExists('paymentReferences', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amountOfMoney
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\AmountOfMoney|null
     */
    public function getAmountOfMoney()
    {
        return $this->container['amountOfMoney'];
    }

    /**
     * Sets amountOfMoney
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\AmountOfMoney|null $amountOfMoney amountOfMoney
     *
     * @return self
     */
    public function setAmountOfMoney($amountOfMoney)
    {
        if (is_null($amountOfMoney)) {
            throw new \InvalidArgumentException('non-nullable amountOfMoney cannot be null');
        }
        $this->container['amountOfMoney'] = $amountOfMoney;

        return $this;
    }

    /**
     * Gets references
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\CheckoutReferences|null
     */
    public function getReferences()
    {
        return $this->container['references'];
    }

    /**
     * Sets references
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\CheckoutReferences|null $references references
     *
     * @return self
     */
    public function setReferences($references)
    {
        if (is_null($references)) {
            throw new \InvalidArgumentException('non-nullable references cannot be null');
        }
        $this->container['references'] = $references;

        return $this;
    }

    /**
     * Gets shipping
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\Shipping|null
     */
    public function getShipping()
    {
        return $this->container['shipping'];
    }

    /**
     * Sets shipping
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\Shipping|null $shipping shipping
     *
     * @return self
     */
    public function setShipping($shipping)
    {
        if (is_null($shipping)) {
            throw new \InvalidArgumentException('non-nullable shipping cannot be null');
        }
        $this->container['shipping'] = $shipping;

        return $this;
    }

    /**
     * Gets shoppingCart
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\ShoppingCartPatch|null
     */
    public function getShoppingCart()
    {
        return $this->container['shoppingCart'];
    }

    /**
     * Sets shoppingCart
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\ShoppingCartPatch|null $shoppingCart shoppingCart
     *
     * @return self
     */
    public function setShoppingCart($shoppingCart)
    {
        if (is_null($shoppingCart)) {
            throw new \InvalidArgumentException('non-nullable shoppingCart cannot be null');
        }
        $this->container['shoppingCart'] = $shoppingCart;

        return $this;
    }

    /**
     * Gets paymentMethodSpecificInput
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\PaymentMethodSpecificInput|null
     */
    public function getPaymentMethodSpecificInput()
    {
        return $this->container['paymentMethodSpecificInput'];
    }

    /**
     * Sets paymentMethodSpecificInput
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\PaymentMethodSpecificInput|null $paymentMethodSpecificInput paymentMethodSpecificInput
     *
     * @return self
     */
    public function setPaymentMethodSpecificInput($paymentMethodSpecificInput)
    {
        if (is_null($paymentMethodSpecificInput)) {
            throw new \InvalidArgumentException('non-nullable paymentMethodSpecificInput cannot be null');
        }
        $this->container['paymentMethodSpecificInput'] = $paymentMethodSpecificInput;

        return $this;
    }

    /**
     * Gets paymentReferences
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\References|null
     */
    public function getPaymentReferences()
    {
        return $this->container['paymentReferences'];
    }

    /**
     * Sets paymentReferences
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\References|null $paymentReferences paymentReferences
     *
     * @return self
     */
    public function setPaymentReferences($paymentReferences)
    {
        if (is_null($paymentReferences)) {
            throw new \InvalidArgumentException('non-nullable paymentReferences cannot be null');
        }
        $this->container['paymentReferences'] = $paymentReferences;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


