<?php
/**
 * PaymentOutput
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Platform API
 *
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayoneCommercePlatform\Sdk\Domain;

use ArrayAccess;
use PayoneCommercePlatform\Sdk\ObjectSerializer;

/**
 * PaymentOutput Class Doc Comment
 *
 * @category Class
 * @description Object containing payment details.
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PaymentOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'amountOfMoney' => '\PayoneCommercePlatform\Sdk\Domain\AmountOfMoney',
        'merchantParameters' => 'string',
        'references' => '\PayoneCommercePlatform\Sdk\Domain\PaymentReferences',
        'cardPaymentMethodSpecificOutput' => '\PayoneCommercePlatform\Sdk\Domain\CardPaymentMethodSpecificOutput',
        'mobilePaymentMethodSpecificOutput' => '\PayoneCommercePlatform\Sdk\Domain\MobilePaymentMethodSpecificOutput',
        'paymentMethod' => 'string',
        'redirectPaymentMethodSpecificOutput' => '\PayoneCommercePlatform\Sdk\Domain\RedirectPaymentMethodSpecificOutput',
        'sepaDirectDebitPaymentMethodSpecificOutput' => '\PayoneCommercePlatform\Sdk\Domain\SepaDirectDebitPaymentMethodSpecificOutput',
        'financingPaymentMethodSpecificOutput' => '\PayoneCommercePlatform\Sdk\Domain\FinancingPaymentMethodSpecificOutput'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'amountOfMoney' => null,
        'merchantParameters' => null,
        'references' => null,
        'cardPaymentMethodSpecificOutput' => null,
        'mobilePaymentMethodSpecificOutput' => null,
        'paymentMethod' => null,
        'redirectPaymentMethodSpecificOutput' => null,
        'sepaDirectDebitPaymentMethodSpecificOutput' => null,
        'financingPaymentMethodSpecificOutput' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'amountOfMoney' => false,
        'merchantParameters' => false,
        'references' => false,
        'cardPaymentMethodSpecificOutput' => false,
        'mobilePaymentMethodSpecificOutput' => false,
        'paymentMethod' => false,
        'redirectPaymentMethodSpecificOutput' => false,
        'sepaDirectDebitPaymentMethodSpecificOutput' => false,
        'financingPaymentMethodSpecificOutput' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amountOfMoney' => 'amountOfMoney',
        'merchantParameters' => 'merchantParameters',
        'references' => 'references',
        'cardPaymentMethodSpecificOutput' => 'cardPaymentMethodSpecificOutput',
        'mobilePaymentMethodSpecificOutput' => 'mobilePaymentMethodSpecificOutput',
        'paymentMethod' => 'paymentMethod',
        'redirectPaymentMethodSpecificOutput' => 'redirectPaymentMethodSpecificOutput',
        'sepaDirectDebitPaymentMethodSpecificOutput' => 'sepaDirectDebitPaymentMethodSpecificOutput',
        'financingPaymentMethodSpecificOutput' => 'financingPaymentMethodSpecificOutput'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amountOfMoney' => 'setAmountOfMoney',
        'merchantParameters' => 'setMerchantParameters',
        'references' => 'setReferences',
        'cardPaymentMethodSpecificOutput' => 'setCardPaymentMethodSpecificOutput',
        'mobilePaymentMethodSpecificOutput' => 'setMobilePaymentMethodSpecificOutput',
        'paymentMethod' => 'setPaymentMethod',
        'redirectPaymentMethodSpecificOutput' => 'setRedirectPaymentMethodSpecificOutput',
        'sepaDirectDebitPaymentMethodSpecificOutput' => 'setSepaDirectDebitPaymentMethodSpecificOutput',
        'financingPaymentMethodSpecificOutput' => 'setFinancingPaymentMethodSpecificOutput'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amountOfMoney' => 'getAmountOfMoney',
        'merchantParameters' => 'getMerchantParameters',
        'references' => 'getReferences',
        'cardPaymentMethodSpecificOutput' => 'getCardPaymentMethodSpecificOutput',
        'mobilePaymentMethodSpecificOutput' => 'getMobilePaymentMethodSpecificOutput',
        'paymentMethod' => 'getPaymentMethod',
        'redirectPaymentMethodSpecificOutput' => 'getRedirectPaymentMethodSpecificOutput',
        'sepaDirectDebitPaymentMethodSpecificOutput' => 'getSepaDirectDebitPaymentMethodSpecificOutput',
        'financingPaymentMethodSpecificOutput' => 'getFinancingPaymentMethodSpecificOutput'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('amountOfMoney', $data ?? [], null);
        $this->setIfExists('merchantParameters', $data ?? [], null);
        $this->setIfExists('references', $data ?? [], null);
        $this->setIfExists('cardPaymentMethodSpecificOutput', $data ?? [], null);
        $this->setIfExists('mobilePaymentMethodSpecificOutput', $data ?? [], null);
        $this->setIfExists('paymentMethod', $data ?? [], null);
        $this->setIfExists('redirectPaymentMethodSpecificOutput', $data ?? [], null);
        $this->setIfExists('sepaDirectDebitPaymentMethodSpecificOutput', $data ?? [], null);
        $this->setIfExists('financingPaymentMethodSpecificOutput', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['merchantParameters']) && (mb_strlen($this->container['merchantParameters']) > 1000)) {
            $invalidProperties[] = "invalid value for 'merchantParameters', the character length must be smaller than or equal to 1000.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amountOfMoney
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\AmountOfMoney|null
     */
    public function getAmountOfMoney()
    {
        return $this->container['amountOfMoney'];
    }

    /**
     * Sets amountOfMoney
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\AmountOfMoney|null $amountOfMoney amountOfMoney
     *
     * @return self
     */
    public function setAmountOfMoney($amountOfMoney)
    {
        if (is_null($amountOfMoney)) {
            throw new \InvalidArgumentException('non-nullable amountOfMoney cannot be null');
        }
        $this->container['amountOfMoney'] = $amountOfMoney;

        return $this;
    }

    /**
     * Gets merchantParameters
     *
     * @return string|null
     */
    public function getMerchantParameters()
    {
        return $this->container['merchantParameters'];
    }

    /**
     * Sets merchantParameters
     *
     * @param string|null $merchantParameters It allows you to store additional parameters for the transaction in JSON format. This field should not contain any personal data.
     *
     * @return self
     */
    public function setMerchantParameters($merchantParameters)
    {
        if (is_null($merchantParameters)) {
            throw new \InvalidArgumentException('non-nullable merchantParameters cannot be null');
        }
        if ((mb_strlen($merchantParameters) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $merchantParameters when calling PaymentOutput., must be smaller than or equal to 1000.');
        }

        $this->container['merchantParameters'] = $merchantParameters;

        return $this;
    }

    /**
     * Gets references
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\PaymentReferences|null
     */
    public function getReferences()
    {
        return $this->container['references'];
    }

    /**
     * Sets references
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\PaymentReferences|null $references references
     *
     * @return self
     */
    public function setReferences($references)
    {
        if (is_null($references)) {
            throw new \InvalidArgumentException('non-nullable references cannot be null');
        }
        $this->container['references'] = $references;

        return $this;
    }

    /**
     * Gets cardPaymentMethodSpecificOutput
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\CardPaymentMethodSpecificOutput|null
     */
    public function getCardPaymentMethodSpecificOutput()
    {
        return $this->container['cardPaymentMethodSpecificOutput'];
    }

    /**
     * Sets cardPaymentMethodSpecificOutput
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\CardPaymentMethodSpecificOutput|null $cardPaymentMethodSpecificOutput cardPaymentMethodSpecificOutput
     *
     * @return self
     */
    public function setCardPaymentMethodSpecificOutput($cardPaymentMethodSpecificOutput)
    {
        if (is_null($cardPaymentMethodSpecificOutput)) {
            throw new \InvalidArgumentException('non-nullable cardPaymentMethodSpecificOutput cannot be null');
        }
        $this->container['cardPaymentMethodSpecificOutput'] = $cardPaymentMethodSpecificOutput;

        return $this;
    }

    /**
     * Gets mobilePaymentMethodSpecificOutput
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\MobilePaymentMethodSpecificOutput|null
     */
    public function getMobilePaymentMethodSpecificOutput()
    {
        return $this->container['mobilePaymentMethodSpecificOutput'];
    }

    /**
     * Sets mobilePaymentMethodSpecificOutput
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\MobilePaymentMethodSpecificOutput|null $mobilePaymentMethodSpecificOutput mobilePaymentMethodSpecificOutput
     *
     * @return self
     */
    public function setMobilePaymentMethodSpecificOutput($mobilePaymentMethodSpecificOutput)
    {
        if (is_null($mobilePaymentMethodSpecificOutput)) {
            throw new \InvalidArgumentException('non-nullable mobilePaymentMethodSpecificOutput cannot be null');
        }
        $this->container['mobilePaymentMethodSpecificOutput'] = $mobilePaymentMethodSpecificOutput;

        return $this;
    }

    /**
     * Gets paymentMethod
     *
     * @return string|null
     */
    public function getPaymentMethod()
    {
        return $this->container['paymentMethod'];
    }

    /**
     * Sets paymentMethod
     *
     * @param string|null $paymentMethod Payment method identifier based on the paymentProductId.
     *
     * @return self
     */
    public function setPaymentMethod($paymentMethod)
    {
        if (is_null($paymentMethod)) {
            throw new \InvalidArgumentException('non-nullable paymentMethod cannot be null');
        }
        $this->container['paymentMethod'] = $paymentMethod;

        return $this;
    }

    /**
     * Gets redirectPaymentMethodSpecificOutput
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\RedirectPaymentMethodSpecificOutput|null
     */
    public function getRedirectPaymentMethodSpecificOutput()
    {
        return $this->container['redirectPaymentMethodSpecificOutput'];
    }

    /**
     * Sets redirectPaymentMethodSpecificOutput
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\RedirectPaymentMethodSpecificOutput|null $redirectPaymentMethodSpecificOutput redirectPaymentMethodSpecificOutput
     *
     * @return self
     */
    public function setRedirectPaymentMethodSpecificOutput($redirectPaymentMethodSpecificOutput)
    {
        if (is_null($redirectPaymentMethodSpecificOutput)) {
            throw new \InvalidArgumentException('non-nullable redirectPaymentMethodSpecificOutput cannot be null');
        }
        $this->container['redirectPaymentMethodSpecificOutput'] = $redirectPaymentMethodSpecificOutput;

        return $this;
    }

    /**
     * Gets sepaDirectDebitPaymentMethodSpecificOutput
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\SepaDirectDebitPaymentMethodSpecificOutput|null
     */
    public function getSepaDirectDebitPaymentMethodSpecificOutput()
    {
        return $this->container['sepaDirectDebitPaymentMethodSpecificOutput'];
    }

    /**
     * Sets sepaDirectDebitPaymentMethodSpecificOutput
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\SepaDirectDebitPaymentMethodSpecificOutput|null $sepaDirectDebitPaymentMethodSpecificOutput sepaDirectDebitPaymentMethodSpecificOutput
     *
     * @return self
     */
    public function setSepaDirectDebitPaymentMethodSpecificOutput($sepaDirectDebitPaymentMethodSpecificOutput)
    {
        if (is_null($sepaDirectDebitPaymentMethodSpecificOutput)) {
            throw new \InvalidArgumentException('non-nullable sepaDirectDebitPaymentMethodSpecificOutput cannot be null');
        }
        $this->container['sepaDirectDebitPaymentMethodSpecificOutput'] = $sepaDirectDebitPaymentMethodSpecificOutput;

        return $this;
    }

    /**
     * Gets financingPaymentMethodSpecificOutput
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\FinancingPaymentMethodSpecificOutput|null
     */
    public function getFinancingPaymentMethodSpecificOutput()
    {
        return $this->container['financingPaymentMethodSpecificOutput'];
    }

    /**
     * Sets financingPaymentMethodSpecificOutput
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\FinancingPaymentMethodSpecificOutput|null $financingPaymentMethodSpecificOutput financingPaymentMethodSpecificOutput
     *
     * @return self
     */
    public function setFinancingPaymentMethodSpecificOutput($financingPaymentMethodSpecificOutput)
    {
        if (is_null($financingPaymentMethodSpecificOutput)) {
            throw new \InvalidArgumentException('non-nullable financingPaymentMethodSpecificOutput cannot be null');
        }
        $this->container['financingPaymentMethodSpecificOutput'] = $financingPaymentMethodSpecificOutput;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
