<?php
/**
 * RedirectPaymentMethodSpecificInput
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Platform API
 *
 * RESTful API for the creation of Commerce Cases with Checkouts and the execution of Payments.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PayoneCommercePlatform\Sdk\Domain;

use ArrayAccess;
use PayoneCommercePlatform\Sdk\ObjectSerializer;

/**
 * RedirectPaymentMethodSpecificInput Class Doc Comment
 *
 * @category Class
 * @description Object containing the specific input details for payments that involve redirects to 3rd parties to complete, like iDeal and PayPal
 * @package  PayoneCommercePlatform\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RedirectPaymentMethodSpecificInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RedirectPaymentMethodSpecificInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'requiresApproval' => 'bool',
        'paymentProcessingToken' => 'string',
        'reportingToken' => 'string',
        'tokenize' => 'bool',
        'paymentProductId' => 'int',
        'paymentProduct840SpecificInput' => '\PayoneCommercePlatform\Sdk\Domain\RedirectPaymentProduct840SpecificInput',
        'redirectionData' => '\PayoneCommercePlatform\Sdk\Domain\RedirectionData'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'requiresApproval' => null,
        'paymentProcessingToken' => null,
        'reportingToken' => null,
        'tokenize' => null,
        'paymentProductId' => 'int32',
        'paymentProduct840SpecificInput' => null,
        'redirectionData' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'requiresApproval' => false,
        'paymentProcessingToken' => false,
        'reportingToken' => false,
        'tokenize' => false,
        'paymentProductId' => false,
        'paymentProduct840SpecificInput' => false,
        'redirectionData' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'requiresApproval' => 'requiresApproval',
        'paymentProcessingToken' => 'paymentProcessingToken',
        'reportingToken' => 'reportingToken',
        'tokenize' => 'tokenize',
        'paymentProductId' => 'paymentProductId',
        'paymentProduct840SpecificInput' => 'paymentProduct840SpecificInput',
        'redirectionData' => 'redirectionData'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'requiresApproval' => 'setRequiresApproval',
        'paymentProcessingToken' => 'setPaymentProcessingToken',
        'reportingToken' => 'setReportingToken',
        'tokenize' => 'setTokenize',
        'paymentProductId' => 'setPaymentProductId',
        'paymentProduct840SpecificInput' => 'setPaymentProduct840SpecificInput',
        'redirectionData' => 'setRedirectionData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'requiresApproval' => 'getRequiresApproval',
        'paymentProcessingToken' => 'getPaymentProcessingToken',
        'reportingToken' => 'getReportingToken',
        'tokenize' => 'getTokenize',
        'paymentProductId' => 'getPaymentProductId',
        'paymentProduct840SpecificInput' => 'getPaymentProduct840SpecificInput',
        'redirectionData' => 'getRedirectionData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('requiresApproval', $data ?? [], null);
        $this->setIfExists('paymentProcessingToken', $data ?? [], null);
        $this->setIfExists('reportingToken', $data ?? [], null);
        $this->setIfExists('tokenize', $data ?? [], null);
        $this->setIfExists('paymentProductId', $data ?? [], null);
        $this->setIfExists('paymentProduct840SpecificInput', $data ?? [], null);
        $this->setIfExists('redirectionData', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['paymentProcessingToken']) && (mb_strlen($this->container['paymentProcessingToken']) > 40)) {
            $invalidProperties[] = "invalid value for 'paymentProcessingToken', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['reportingToken']) && (mb_strlen($this->container['reportingToken']) > 40)) {
            $invalidProperties[] = "invalid value for 'reportingToken', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['paymentProductId']) && ($this->container['paymentProductId'] > 99999)) {
            $invalidProperties[] = "invalid value for 'paymentProductId', must be smaller than or equal to 99999.";
        }

        if (!is_null($this->container['paymentProductId']) && ($this->container['paymentProductId'] < 0)) {
            $invalidProperties[] = "invalid value for 'paymentProductId', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets requiresApproval
     *
     * @return bool|null
     */
    public function getRequiresApproval()
    {
        return $this->container['requiresApproval'];
    }

    /**
     * Sets requiresApproval
     *
     * @param bool|null $requiresApproval * true = the payment requires approval before the funds will be captured using the Approve payment or Capture payment API * false = the payment does not require approval, and the funds will be captured automatically  If the parameter is not provided in the request, the default value will be true
     *
     * @return self
     */
    public function setRequiresApproval($requiresApproval)
    {
        if (is_null($requiresApproval)) {
            throw new \InvalidArgumentException('non-nullable requiresApproval cannot be null');
        }
        $this->container['requiresApproval'] = $requiresApproval;

        return $this;
    }

    /**
     * Gets paymentProcessingToken
     *
     * @return string|null
     */
    public function getPaymentProcessingToken()
    {
        return $this->container['paymentProcessingToken'];
    }

    /**
     * Sets paymentProcessingToken
     *
     * @param string|null $paymentProcessingToken ID of the token to use to create the payment.
     *
     * @return self
     */
    public function setPaymentProcessingToken($paymentProcessingToken)
    {
        if (is_null($paymentProcessingToken)) {
            throw new \InvalidArgumentException('non-nullable paymentProcessingToken cannot be null');
        }
        if ((mb_strlen($paymentProcessingToken) > 40)) {
            throw new \InvalidArgumentException('invalid length for $paymentProcessingToken when calling RedirectPaymentMethodSpecificInput., must be smaller than or equal to 40.');
        }

        $this->container['paymentProcessingToken'] = $paymentProcessingToken;

        return $this;
    }

    /**
     * Gets reportingToken
     *
     * @return string|null
     */
    public function getReportingToken()
    {
        return $this->container['reportingToken'];
    }

    /**
     * Sets reportingToken
     *
     * @param string|null $reportingToken Token to identify the card in the reporting.
     *
     * @return self
     */
    public function setReportingToken($reportingToken)
    {
        if (is_null($reportingToken)) {
            throw new \InvalidArgumentException('non-nullable reportingToken cannot be null');
        }
        if ((mb_strlen($reportingToken) > 40)) {
            throw new \InvalidArgumentException('invalid length for $reportingToken when calling RedirectPaymentMethodSpecificInput., must be smaller than or equal to 40.');
        }

        $this->container['reportingToken'] = $reportingToken;

        return $this;
    }

    /**
     * Gets tokenize
     *
     * @return bool|null
     */
    public function getTokenize()
    {
        return $this->container['tokenize'];
    }

    /**
     * Sets tokenize
     *
     * @param bool|null $tokenize Indicates if this transaction should be tokenized   * true - Tokenize the transaction.   * false - Do not tokenize the transaction, unless it would be tokenized by other means such as auto- tokenization of recurring payments. example: false
     *
     * @return self
     */
    public function setTokenize($tokenize)
    {
        if (is_null($tokenize)) {
            throw new \InvalidArgumentException('non-nullable tokenize cannot be null');
        }
        $this->container['tokenize'] = $tokenize;

        return $this;
    }

    /**
     * Gets paymentProductId
     *
     * @return int|null
     */
    public function getPaymentProductId()
    {
        return $this->container['paymentProductId'];
    }

    /**
     * Sets paymentProductId
     *
     * @param int|null $paymentProductId Payment product identifier - please check product documentation for a full overview of possible values.
     *
     * @return self
     */
    public function setPaymentProductId($paymentProductId)
    {
        if (is_null($paymentProductId)) {
            throw new \InvalidArgumentException('non-nullable paymentProductId cannot be null');
        }

        if (($paymentProductId > 99999)) {
            throw new \InvalidArgumentException('invalid value for $paymentProductId when calling RedirectPaymentMethodSpecificInput., must be smaller than or equal to 99999.');
        }
        if (($paymentProductId < 0)) {
            throw new \InvalidArgumentException('invalid value for $paymentProductId when calling RedirectPaymentMethodSpecificInput., must be bigger than or equal to 0.');
        }

        $this->container['paymentProductId'] = $paymentProductId;

        return $this;
    }

    /**
     * Gets paymentProduct840SpecificInput
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\RedirectPaymentProduct840SpecificInput|null
     */
    public function getPaymentProduct840SpecificInput()
    {
        return $this->container['paymentProduct840SpecificInput'];
    }

    /**
     * Sets paymentProduct840SpecificInput
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\RedirectPaymentProduct840SpecificInput|null $paymentProduct840SpecificInput paymentProduct840SpecificInput
     *
     * @return self
     */
    public function setPaymentProduct840SpecificInput($paymentProduct840SpecificInput)
    {
        if (is_null($paymentProduct840SpecificInput)) {
            throw new \InvalidArgumentException('non-nullable paymentProduct840SpecificInput cannot be null');
        }
        $this->container['paymentProduct840SpecificInput'] = $paymentProduct840SpecificInput;

        return $this;
    }

    /**
     * Gets redirectionData
     *
     * @return \PayoneCommercePlatform\Sdk\Domain\RedirectionData|null
     */
    public function getRedirectionData()
    {
        return $this->container['redirectionData'];
    }

    /**
     * Sets redirectionData
     *
     * @param \PayoneCommercePlatform\Sdk\Domain\RedirectionData|null $redirectionData redirectionData
     *
     * @return self
     */
    public function setRedirectionData($redirectionData)
    {
        if (is_null($redirectionData)) {
            throw new \InvalidArgumentException('non-nullable redirectionData cannot be null');
        }
        $this->container['redirectionData'] = $redirectionData;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
