<?php

namespace PayoneCommercePlatform\Sdk\Models;

/**
 * @description Current high-level status of the payment in a human-readable form.
 */
enum StatusValue: string
{
    case CREATED = 'CREATED';
    case CANCELLED = 'CANCELLED';
    case REJECTED = 'REJECTED';
    case REJECTED_CAPTURE = 'REJECTED_CAPTURE';
    case REDIRECTED = 'REDIRECTED';
    case PENDING_PAYMENT = 'PENDING_PAYMENT';
    case PENDING_COMPLETION = 'PENDING_COMPLETION';
    case PENDING_CAPTURE = 'PENDING_CAPTURE';
    case AUTHORIZATION_REQUESTED = 'AUTHORIZATION_REQUESTED';
    case CAPTURE_REQUESTED = 'CAPTURE_REQUESTED';
    case CAPTURED = 'CAPTURED';
    case REVERSED = 'REVERSED';
    case REFUND_REQUESTED = 'REFUND_REQUESTED';
    case REFUNDED = 'REFUNDED';
    case REJECTED_REFUND = 'REJECTED_REFUND';
    case CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED';
    case PAUSED = 'PAUSED';
    case CHARGEBACKED = 'CHARGEBACKED';
    case CHARGEBACK_REVERSED = 'CHARGEBACK_REVERSED';
    case ACCOUNT_CREDITED = 'ACCOUNT_CREDITED';
    case ACCOUNT_DEBITED = 'ACCOUNT_DEBITED';
    case PAYOUT_REQUESTED = 'PAYOUT_REQUESTED';
    case REJECTED_CREDIT = 'REJECTED_CREDIT';
}
